### ISSUE TITLE
Discrepancy in the semi-supervised results for 10% data

### ISSUE THREAD

**Issue by shoaibahmed** [facebookresearch/barlowtwins#14]
Hi,

I was able to reproduce your linear probe results for BarlowTwins:
`{"epoch": 99, "acc1": 73.266, "acc5": 91.094, "best_acc1": 73.29, "best_acc5": 91.108}.`

I have also computed the semi-supervised results. Although the results for 1% data match, the results for 10% data are slightly different. I used the same hyperparameters for 10% as 1% data since you only mentioned the parameters for 1%. Maybe that was the difference. If the parameters are different, can you please clarify the parameters for 10% data?

1% data: `{"epoch": 19, "acc1": 55.09, "acc5": 79.894, "best_acc1": 55.102, "best_acc5": 79.894}`
10% data: `{"epoch": 19, "acc1": 68.89, "acc5": 88.966, "best_acc1": 68.89, "best_acc5": 88.966}`

**Comment by jzbontar** [comment]
Hello,

we used the same hyper-parameters for 1% and 10% in the semi-supervised results.

The difference between the numbers reported in the paper (acc1 = 69.7%, acc5= 89.3%) and the numbers for the open-sourced model (acc1 = 68.89%, acc5 = 88.966%) are small enough that I would put them down to the randomness of training. However, we really should (and we plan to) perform multiple training runs of Barlow Twins so that we can provide error bars for our results.
