### ISSUE TITLE
Evaluating a checkpoint

### ISSUE THREAD

**Issue by kartikgupta-at-anu** [facebookresearch/barlowtwins#20]
I am trying to evaluate a checkpoint while training but when i use the evaluation script, I get following error:
 
AttributeError: Can't get attribute 'exclude_bias_and_norm' on <module '__mp_main__' from '/home/ubuntu/Projects/barlowtwins/evaluate.py'>

Can you please have a look?

**Comment by jzbontar** [comment]
The training script, main.py, is not written in a way that would allow evaluation during training, but there is an easy fix. You can indent the following 4 lines https://github.com/facebookresearch/barlowtwins/blob/main/main.py#L139-L142 and the training script will create a checkpoint after each epoch, instead of creating only one checkpoint at the end of training. Then pass the checkpoint file, resnet50.pth, to the evaluation script.

**Comment by CoinCheung** [comment]
@jzbontar 
Hi, 

Would you please update checkpoint file? I have same problem when I run this:
```
state = torch.load('checkpoint.pth')
```
