### ISSUE TITLE
Single GPU Training

### ISSUE THREAD

**Issue by mmaaz60** [facebookresearch/barlowtwins#3]
How can I train the model on a Single GPU machine? Thanks

**Comment by jzbontar** [comment]
If you run `main.py` on a machine with a single GPU it will train using only that one GPU. If you plan on training on ImageNet-size images (3x224x224) you will also need to reduce the batch size to 128, 64, or even 32, since you won't be able to fit a batch size of 2048 into a single GPU. 

When using such a small batch size, it also might make sense to replace LARS by SGD.
